version: '3'
services:
  linkious-server:
    build:
      context: ./linktious-server
    command: ["sh", "-c", "pip install debugpy -t /tmp && python /tmp/debugpy --listen 0.0.0.0:5678 -m uvicorn src.app:app --host 0.0.0.0 --port 8000 --reload"]
    volumes:
      - ./linktious-server/src/:/app/src
    restart: always
    ports:
      - 8000:8000
      - 5678:5678
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
        interval: 30s
        timeout: 10s
        retries: 5
  linkious-client:
    build:
      context: ./linktious-client
    volumes:
      - ./linktious-client/:/app/
    restart: always
    environment: 
      - BACKEND_URL=http://linktious-server:8000/
    ports:
      - 3000:3000
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:3000"]
        interval: 30s
        timeout: 10s
        retries: 5